name: electrolyte-ml
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - rdkit
  - scikit-learn=1.9.1
  - xgboost=3.4.1
  - pandas
  - matplotlib
  - numpy=2.5.3
  - pyyaml
  - requests
  - thermoml-io
  - jupyterlab
  - pytest
  - pip:
      - ruff
