"""Verify that every figure the manuscript cites exists and still re-derives.

The paper's figure section names, for each figure, the artifact that holds the
rendered file and (for the two figures generated by a dedicated probe) the probe
that writes it. Nothing else in CI checks that those paths exist, so a renamed
artifact or a deleted script would leave the manuscript citing a file that is
not in the repository.

This verifier

* parses the figure section and requires consecutive numbering from 1;
* requires every cited artifact and script to exist;
* runs the two figure probes with ``--check`` so their committed summaries must
  match the rosters and the conformal probe summary they are derived from.

Usage:
    python scripts/verify_paper_figures.py
    python scripts/verify_paper_figures.py --json
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]

FIGURE_SECTION = REPOSITORY_ROOT / "paper" / "benchmark_and_figures.md"
EXPECTED_FIGURE_COUNT = 6

# Figures rendered by a dedicated probe, which CI re-runs via --check.
PROBE_CHECKS = (
    "probes/paper_figure_dataset_growth.py",
    "probes/paper_figure_conformal_strata.py",
)

ARTIFACT_RE = re.compile(r"Artifact:\s*`([^`]+)`")
SCRIPT_RE = re.compile(r"Script:\s*`python\s+([^\s`]+)")
FIGURE_RE = re.compile(r"^\*\*Figure\s+(\d+)\.", re.MULTILINE)


def parse_figure_section(text: str) -> list[dict]:
    """Return one record per figure in the order the section lists them."""
    matches = list(FIGURE_RE.finditer(text))
    figures = []
    for index, match in enumerate(matches):
        end = matches[index + 1].start() if index + 1 < len(matches) else len(text)
        block = text[match.end():end]
        figures.append(
            {
                "number": int(match.group(1)),
                "artifacts": ARTIFACT_RE.findall(block),
                "scripts": SCRIPT_RE.findall(block),
            }
        )
    return figures


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--json", action="store_true", help="emit a JSON report")
    args = parser.parse_args(argv)

    errors: list[str] = []
    text = FIGURE_SECTION.read_text(encoding="utf-8-sig")
    figures = parse_figure_section(text)

    if len(figures) != EXPECTED_FIGURE_COUNT:
        errors.append(
            f"the figure section lists {len(figures)} figures, expected {EXPECTED_FIGURE_COUNT}"
        )
    numbers = [figure["number"] for figure in figures]
    if numbers != list(range(1, len(figures) + 1)):
        errors.append(f"figure numbering is {numbers}, expected consecutive from 1")

    for figure in figures:
        label = f"Figure {figure['number']}"
        if not figure["artifacts"]:
            errors.append(f"{label}: no Artifact path is cited")
        for relative in figure["artifacts"] + figure["scripts"]:
            if not (REPOSITORY_ROOT / relative).is_file():
                errors.append(f"{label}: cited path does not exist: {relative}")

    probe_results = []
    for relative in PROBE_CHECKS:
        completed = subprocess.run(
            [sys.executable, relative, "--check"],
            cwd=REPOSITORY_ROOT,
            capture_output=True,
            text=True,
            check=False,
        )
        probe_results.append(
            {
                "script": relative,
                "returncode": completed.returncode,
                "stdout": completed.stdout.strip(),
                "stderr": completed.stderr.strip(),
            }
        )
        if completed.returncode != 0:
            errors.append(
                f"{relative} --check failed: "
                f"{(completed.stderr or completed.stdout).strip()}"
            )

    report = {
        "figure_count": len(figures),
        "figures": figures,
        "probe_checks": probe_results,
        "errors": errors,
    }
    if args.json:
        print(json.dumps(report, indent=2, ensure_ascii=False))
    elif errors:
        for error in errors:
            print(f"FAIL: {error}", file=sys.stderr)
    else:
        for figure in figures:
            print(
                f"  Figure {figure['number']}: "
                + ", ".join(figure["artifacts"] + figure["scripts"])
            )
        for result in probe_results:
            print(f"  {result['script']} --check: {result['stdout']}")
        print(f"PASS: {len(figures)} figures are cited, present and reproducible")
    return 1 if errors else 0


if __name__ == "__main__":
    raise SystemExit(main())